package com.doto.domain.festival.entity.code;

import com.doto.domain.festival.entity.enums.Region;
import java.util.List;

// TourAPI ldongCode2 실제 응답 기준, docs/TourApiDoc.md 지역 코드 참고
public final class GunguCodes {

    private static final List<GunguCode> CODES = List.of(
            new GunguCode(Region.서울특별시, "110", "종로구"),
            new GunguCode(Region.서울특별시, "140", "중구"),
            new GunguCode(Region.서울특별시, "170", "용산구"),
            new GunguCode(Region.서울특별시, "200", "성동구"),
            new GunguCode(Region.서울특별시, "215", "광진구"),
            new GunguCode(Region.서울특별시, "230", "동대문구"),
            new GunguCode(Region.서울특별시, "260", "중랑구"),
            new GunguCode(Region.서울특별시, "290", "성북구"),
            new GunguCode(Region.서울특별시, "305", "강북구"),
            new GunguCode(Region.서울특별시, "320", "도봉구"),
            new GunguCode(Region.서울특별시, "350", "노원구"),
            new GunguCode(Region.서울특별시, "380", "은평구"),
            new GunguCode(Region.서울특별시, "410", "서대문구"),
            new GunguCode(Region.서울특별시, "440", "마포구"),
            new GunguCode(Region.서울특별시, "470", "양천구"),
            new GunguCode(Region.서울특별시, "500", "강서구"),
            new GunguCode(Region.서울특별시, "530", "구로구"),
            new GunguCode(Region.서울특별시, "545", "금천구"),
            new GunguCode(Region.서울특별시, "560", "영등포구"),
            new GunguCode(Region.서울특별시, "590", "동작구"),
            new GunguCode(Region.서울특별시, "620", "관악구"),
            new GunguCode(Region.서울특별시, "650", "서초구"),
            new GunguCode(Region.서울특별시, "680", "강남구"),
            new GunguCode(Region.서울특별시, "710", "송파구"),
            new GunguCode(Region.서울특별시, "740", "강동구"),
            new GunguCode(Region.인천광역시, "125", "제물포구"),
            new GunguCode(Region.인천광역시, "155", "영종구"),
            new GunguCode(Region.인천광역시, "177", "미추홀구"),
            new GunguCode(Region.인천광역시, "185", "연수구"),
            new GunguCode(Region.인천광역시, "200", "남동구"),
            new GunguCode(Region.인천광역시, "237", "부평구"),
            new GunguCode(Region.인천광역시, "245", "계양구"),
            new GunguCode(Region.인천광역시, "275", "서해구"),
            new GunguCode(Region.인천광역시, "290", "검단구"),
            new GunguCode(Region.인천광역시, "710", "강화군"),
            new GunguCode(Region.인천광역시, "720", "옹진군"),
            new GunguCode(Region.대전광역시, "110", "동구"),
            new GunguCode(Region.대전광역시, "140", "중구"),
            new GunguCode(Region.대전광역시, "170", "서구"),
            new GunguCode(Region.대전광역시, "200", "유성구"),
            new GunguCode(Region.대전광역시, "230", "대덕구"),
            new GunguCode(Region.대구광역시, "110", "중구"),
            new GunguCode(Region.대구광역시, "140", "동구"),
            new GunguCode(Region.대구광역시, "170", "서구"),
            new GunguCode(Region.대구광역시, "200", "남구"),
            new GunguCode(Region.대구광역시, "230", "북구"),
            new GunguCode(Region.대구광역시, "260", "수성구"),
            new GunguCode(Region.대구광역시, "290", "달서구"),
            new GunguCode(Region.대구광역시, "710", "달성군"),
            new GunguCode(Region.대구광역시, "720", "군위군"),
            new GunguCode(Region.전남광주통합특별시, "110", "목포시"),
            new GunguCode(Region.전남광주통합특별시, "130", "여수시"),
            new GunguCode(Region.전남광주통합특별시, "150", "순천시"),
            new GunguCode(Region.전남광주통합특별시, "170", "나주시"),
            new GunguCode(Region.전남광주통합특별시, "190", "광양시"),
            new GunguCode(Region.전남광주통합특별시, "210", "동구"),
            new GunguCode(Region.전남광주통합특별시, "240", "서구"),
            new GunguCode(Region.전남광주통합특별시, "270", "남구"),
            new GunguCode(Region.전남광주통합특별시, "300", "북구"),
            new GunguCode(Region.전남광주통합특별시, "330", "광산구"),
            new GunguCode(Region.전남광주통합특별시, "710", "담양군"),
            new GunguCode(Region.전남광주통합특별시, "720", "곡성군"),
            new GunguCode(Region.전남광주통합특별시, "730", "구례군"),
            new GunguCode(Region.전남광주통합특별시, "740", "고흥군"),
            new GunguCode(Region.전남광주통합특별시, "750", "보성군"),
            new GunguCode(Region.전남광주통합특별시, "760", "화순군"),
            new GunguCode(Region.전남광주통합특별시, "770", "장흥군"),
            new GunguCode(Region.전남광주통합특별시, "780", "강진군"),
            new GunguCode(Region.전남광주통합특별시, "790", "해남군"),
            new GunguCode(Region.전남광주통합특별시, "800", "영암군"),
            new GunguCode(Region.전남광주통합특별시, "810", "무안군"),
            new GunguCode(Region.전남광주통합특별시, "820", "함평군"),
            new GunguCode(Region.전남광주통합특별시, "830", "영광군"),
            new GunguCode(Region.전남광주통합특별시, "840", "장성군"),
            new GunguCode(Region.전남광주통합특별시, "850", "완도군"),
            new GunguCode(Region.부산광역시, "110", "중구"),
            new GunguCode(Region.부산광역시, "140", "서구"),
            new GunguCode(Region.부산광역시, "170", "동구"),
            new GunguCode(Region.부산광역시, "200", "영도구"),
            new GunguCode(Region.부산광역시, "230", "부산진구"),
            new GunguCode(Region.부산광역시, "260", "동래구"),
            new GunguCode(Region.부산광역시, "290", "남구"),
            new GunguCode(Region.부산광역시, "320", "북구"),
            new GunguCode(Region.부산광역시, "350", "해운대구"),
            new GunguCode(Region.부산광역시, "380", "사하구"),
            new GunguCode(Region.부산광역시, "410", "금정구"),
            new GunguCode(Region.부산광역시, "440", "강서구"),
            new GunguCode(Region.부산광역시, "470", "연제구"),
            new GunguCode(Region.부산광역시, "500", "수영구"),
            new GunguCode(Region.부산광역시, "530", "사상구"),
            new GunguCode(Region.부산광역시, "710", "기장군"),
            new GunguCode(Region.울산광역시, "110", "중구"),
            new GunguCode(Region.울산광역시, "140", "남구"),
            new GunguCode(Region.울산광역시, "170", "동구"),
            new GunguCode(Region.울산광역시, "200", "북구"),
            new GunguCode(Region.울산광역시, "710", "울주군"),
            new GunguCode(Region.세종특별자치시, "36110", "세종특별자치시"),
            new GunguCode(Region.경기도, "110", "수원시"),
            new GunguCode(Region.경기도, "111", "수원시 장안구"),
            new GunguCode(Region.경기도, "113", "수원시 권선구"),
            new GunguCode(Region.경기도, "115", "수원시 팔달구"),
            new GunguCode(Region.경기도, "117", "수원시 영통구"),
            new GunguCode(Region.경기도, "130", "성남시"),
            new GunguCode(Region.경기도, "131", "성남시 수정구"),
            new GunguCode(Region.경기도, "133", "성남시 중원구"),
            new GunguCode(Region.경기도, "135", "성남시 분당구"),
            new GunguCode(Region.경기도, "150", "의정부시"),
            new GunguCode(Region.경기도, "170", "안양시"),
            new GunguCode(Region.경기도, "171", "안양시 만안구"),
            new GunguCode(Region.경기도, "173", "안양시 동안구"),
            new GunguCode(Region.경기도, "190", "부천시"),
            new GunguCode(Region.경기도, "192", "부천시 원미구"),
            new GunguCode(Region.경기도, "194", "부천시 소사구"),
            new GunguCode(Region.경기도, "196", "부천시 오정구"),
            new GunguCode(Region.경기도, "210", "광명시"),
            new GunguCode(Region.경기도, "220", "평택시"),
            new GunguCode(Region.경기도, "250", "동두천시"),
            new GunguCode(Region.경기도, "270", "안산시"),
            new GunguCode(Region.경기도, "271", "안산시 상록구"),
            new GunguCode(Region.경기도, "273", "안산시 단원구"),
            new GunguCode(Region.경기도, "280", "고양시"),
            new GunguCode(Region.경기도, "281", "고양시 덕양구"),
            new GunguCode(Region.강원특별자치도, "110", "춘천시"),
            new GunguCode(Region.강원특별자치도, "130", "원주시"),
            new GunguCode(Region.강원특별자치도, "150", "강릉시"),
            new GunguCode(Region.강원특별자치도, "170", "동해시"),
            new GunguCode(Region.강원특별자치도, "190", "태백시"),
            new GunguCode(Region.강원특별자치도, "210", "속초시"),
            new GunguCode(Region.강원특별자치도, "230", "삼척시"),
            new GunguCode(Region.강원특별자치도, "720", "홍천군"),
            new GunguCode(Region.강원특별자치도, "730", "횡성군"),
            new GunguCode(Region.강원특별자치도, "750", "영월군"),
            new GunguCode(Region.강원특별자치도, "760", "평창군"),
            new GunguCode(Region.강원특별자치도, "770", "정선군"),
            new GunguCode(Region.강원특별자치도, "780", "철원군"),
            new GunguCode(Region.강원특별자치도, "790", "화천군"),
            new GunguCode(Region.강원특별자치도, "800", "양구군"),
            new GunguCode(Region.강원특별자치도, "810", "인제군"),
            new GunguCode(Region.강원특별자치도, "820", "고성군"),
            new GunguCode(Region.강원특별자치도, "830", "양양군"),
            new GunguCode(Region.충청북도, "110", "청주시"),
            new GunguCode(Region.충청북도, "111", "청주시 상당구"),
            new GunguCode(Region.충청북도, "112", "청주시 서원구"),
            new GunguCode(Region.충청북도, "113", "청주시 흥덕구"),
            new GunguCode(Region.충청북도, "114", "청주시 청원구"),
            new GunguCode(Region.충청북도, "130", "충주시"),
            new GunguCode(Region.충청북도, "150", "제천시"),
            new GunguCode(Region.충청북도, "720", "보은군"),
            new GunguCode(Region.충청북도, "730", "옥천군"),
            new GunguCode(Region.충청북도, "740", "영동군"),
            new GunguCode(Region.충청북도, "745", "증평군"),
            new GunguCode(Region.충청북도, "750", "진천군"),
            new GunguCode(Region.충청북도, "760", "괴산군"),
            new GunguCode(Region.충청북도, "770", "음성군"),
            new GunguCode(Region.충청북도, "800", "단양군"),
            new GunguCode(Region.충청남도, "130", "천안시"),
            new GunguCode(Region.충청남도, "131", "천안시 동남구"),
            new GunguCode(Region.충청남도, "133", "천안시 서북구"),
            new GunguCode(Region.충청남도, "150", "공주시"),
            new GunguCode(Region.충청남도, "180", "보령시"),
            new GunguCode(Region.충청남도, "200", "아산시"),
            new GunguCode(Region.충청남도, "210", "서산시"),
            new GunguCode(Region.충청남도, "230", "논산시"),
            new GunguCode(Region.충청남도, "250", "계룡시"),
            new GunguCode(Region.충청남도, "270", "당진시"),
            new GunguCode(Region.충청남도, "710", "금산군"),
            new GunguCode(Region.충청남도, "760", "부여군"),
            new GunguCode(Region.충청남도, "770", "서천군"),
            new GunguCode(Region.충청남도, "790", "청양군"),
            new GunguCode(Region.충청남도, "800", "홍성군"),
            new GunguCode(Region.충청남도, "810", "예산군"),
            new GunguCode(Region.충청남도, "825", "태안군"),
            new GunguCode(Region.경상북도, "110", "포항시"),
            new GunguCode(Region.경상북도, "111", "포항시 남구"),
            new GunguCode(Region.경상북도, "113", "포항시 북구"),
            new GunguCode(Region.경상북도, "130", "경주시"),
            new GunguCode(Region.경상북도, "150", "김천시"),
            new GunguCode(Region.경상북도, "170", "안동시"),
            new GunguCode(Region.경상북도, "190", "구미시"),
            new GunguCode(Region.경상북도, "210", "영주시"),
            new GunguCode(Region.경상북도, "230", "영천시"),
            new GunguCode(Region.경상북도, "250", "상주시"),
            new GunguCode(Region.경상북도, "280", "문경시"),
            new GunguCode(Region.경상북도, "290", "경산시"),
            new GunguCode(Region.경상북도, "730", "의성군"),
            new GunguCode(Region.경상북도, "750", "청송군"),
            new GunguCode(Region.경상북도, "760", "영양군"),
            new GunguCode(Region.경상북도, "770", "영덕군"),
            new GunguCode(Region.경상북도, "820", "청도군"),
            new GunguCode(Region.경상북도, "830", "고령군"),
            new GunguCode(Region.경상북도, "840", "성주군"),
            new GunguCode(Region.경상북도, "850", "칠곡군"),
            new GunguCode(Region.경상북도, "900", "예천군"),
            new GunguCode(Region.경상북도, "920", "봉화군"),
            new GunguCode(Region.경상북도, "930", "울진군"),
            new GunguCode(Region.경상북도, "940", "울릉군"),
            new GunguCode(Region.경상남도, "120", "창원시"),
            new GunguCode(Region.경상남도, "121", "창원시 의창구"),
            new GunguCode(Region.경상남도, "123", "창원시 성산구"),
            new GunguCode(Region.경상남도, "125", "창원시 마산합포구"),
            new GunguCode(Region.경상남도, "127", "창원시 마산회원구"),
            new GunguCode(Region.경상남도, "129", "창원시 진해구"),
            new GunguCode(Region.경상남도, "170", "진주시"),
            new GunguCode(Region.경상남도, "220", "통영시"),
            new GunguCode(Region.경상남도, "240", "사천시"),
            new GunguCode(Region.경상남도, "250", "김해시"),
            new GunguCode(Region.경상남도, "270", "밀양시"),
            new GunguCode(Region.경상남도, "310", "거제시"),
            new GunguCode(Region.경상남도, "330", "양산시"),
            new GunguCode(Region.경상남도, "720", "의령군"),
            new GunguCode(Region.경상남도, "730", "함안군"),
            new GunguCode(Region.경상남도, "740", "창녕군"),
            new GunguCode(Region.경상남도, "820", "고성군"),
            new GunguCode(Region.경상남도, "840", "남해군"),
            new GunguCode(Region.경상남도, "850", "하동군"),
            new GunguCode(Region.경상남도, "860", "산청군"),
            new GunguCode(Region.경상남도, "870", "함양군"),
            new GunguCode(Region.경상남도, "880", "거창군"),
            new GunguCode(Region.경상남도, "890", "합천군"),
            new GunguCode(Region.제주특별자치도, "110", "제주시"),
            new GunguCode(Region.제주특별자치도, "130", "서귀포시"),
            new GunguCode(Region.전북특별자치도, "110", "전주시"),
            new GunguCode(Region.전북특별자치도, "111", "전주시 완산구"),
            new GunguCode(Region.전북특별자치도, "113", "전주시 덕진구"),
            new GunguCode(Region.전북특별자치도, "130", "군산시"),
            new GunguCode(Region.전북특별자치도, "140", "익산시"),
            new GunguCode(Region.전북특별자치도, "180", "정읍시"),
            new GunguCode(Region.전북특별자치도, "190", "남원시"),
            new GunguCode(Region.전북특별자치도, "210", "김제시"),
            new GunguCode(Region.전북특별자치도, "710", "완주군"),
            new GunguCode(Region.전북특별자치도, "720", "진안군"),
            new GunguCode(Region.전북특별자치도, "730", "무주군"),
            new GunguCode(Region.전북특별자치도, "740", "장수군"),
            new GunguCode(Region.전북특별자치도, "750", "임실군"),
            new GunguCode(Region.전북특별자치도, "770", "순창군"),
            new GunguCode(Region.전북특별자치도, "790", "고창군"),
            new GunguCode(Region.전북특별자치도, "800", "부안군")
    );

    private GunguCodes() {
    }

    public static String findName(Region region, String code) {
        return CODES.stream()
                .filter(gunguCode -> gunguCode.region() == region && gunguCode.code().equals(code))
                .map(GunguCode::name)
                .findFirst()
                .orElse(null);
    }
}
