CREATE TABLE users (
    user_id BIGINT NOT NULL,
    nickname VARCHAR(30) NOT NULL,
    status VARCHAR(15) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

CREATE TABLE general_auth_accounts (
    user_id BIGINT NOT NULL,
    email VARCHAR(190) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_general_auth_accounts PRIMARY KEY (user_id),
    CONSTRAINT fk_general_auth_accounts_user FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT uk_general_auth_accounts_email UNIQUE (email)
);

CREATE TABLE social_auth_accounts (
    social_account_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    provider VARCHAR(30) NOT NULL,
    issuer VARCHAR(255),
    external_id VARCHAR(255) NOT NULL,
    email VARCHAR(190),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_social_auth_accounts PRIMARY KEY (social_account_id),
    CONSTRAINT fk_social_auth_accounts_user FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT uk_social_auth_accounts_provider_external_id UNIQUE (provider, external_id)
);

CREATE INDEX idx_social_auth_accounts_user_id ON social_auth_accounts (user_id);
