CREATE TABLE members (
    member_id BIGINT NOT NULL,
    nickname VARCHAR(30) NOT NULL,
    status VARCHAR(15) NOT NULL DEFAULT 'ACTIVE',
    role VARCHAR(15) NOT NULL DEFAULT 'USER',
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_members PRIMARY KEY (member_id)
);

CREATE TABLE general_auth_accounts (
    member_id BIGINT NOT NULL,
    email VARCHAR(190) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_general_auth_accounts PRIMARY KEY (member_id),
    CONSTRAINT fk_general_auth_accounts_member FOREIGN KEY (member_id) REFERENCES members (member_id),
    CONSTRAINT uk_general_auth_accounts_email UNIQUE (email)
);

CREATE TABLE social_auth_accounts (
    social_account_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    member_id BIGINT NOT NULL,
    provider VARCHAR(30) NOT NULL,
    issuer VARCHAR(255),
    external_id VARCHAR(255) NOT NULL,
    email VARCHAR(190),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_social_auth_accounts PRIMARY KEY (social_account_id),
    CONSTRAINT fk_social_auth_accounts_member FOREIGN KEY (member_id) REFERENCES members (member_id),
    CONSTRAINT uk_social_auth_accounts_provider_external_id UNIQUE (provider, external_id)
);

CREATE INDEX idx_social_auth_accounts_member_id ON social_auth_accounts (member_id);

CREATE TABLE refresh_tokens (
    refresh_token_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    member_id BIGINT NOT NULL,
    token_hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (refresh_token_id),
    CONSTRAINT fk_refresh_tokens_member FOREIGN KEY (member_id) REFERENCES members (member_id),
    CONSTRAINT uk_refresh_tokens_token_hash UNIQUE (token_hash)
);

CREATE INDEX idx_refresh_tokens_member_id ON refresh_tokens (member_id);
