ALTER TABLE festivals
    DROP COLUMN area_code,
    DROP COLUMN region_code,
    DROP COLUMN sigungu_code,
    ADD COLUMN l_dong_regn_cd VARCHAR(10),
    ADD COLUMN l_dong_signgu_cd VARCHAR(10),
    ADD COLUMN content_id BIGINT,
    ADD COLUMN operation_hours VARCHAR(50),
    ADD COLUMN program TEXT;

ALTER TABLE festivals
    ALTER COLUMN phone TYPE VARCHAR(100);

ALTER TABLE tour_spots
    ADD COLUMN content_id BIGINT,
    ADD COLUMN image_url TEXT,
    ADD COLUMN address VARCHAR(255),
    ADD COLUMN l_dong_regn_cd VARCHAR(10),
    ADD COLUMN l_dong_signgu_cd VARCHAR(10),
    ADD COLUMN phone VARCHAR(100),
    ADD COLUMN api_modified_at VARCHAR(14);

CREATE UNIQUE INDEX uk_festivals_content_id ON festivals (content_id) WHERE content_id IS NOT NULL;
CREATE UNIQUE INDEX uk_tour_spots_content_id ON tour_spots (content_id) WHERE content_id IS NOT NULL;

CREATE TABLE festival_tour_spots (
    festival_tour_spot_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    festival_id BIGINT NOT NULL,
    tour_spot_id BIGINT NOT NULL,
    CONSTRAINT pk_festival_tour_spots PRIMARY KEY (festival_tour_spot_id),
    CONSTRAINT fk_festival_tour_spots_festival FOREIGN KEY (festival_id) REFERENCES festivals (festival_id),
    CONSTRAINT fk_festival_tour_spots_tour_spot FOREIGN KEY (tour_spot_id) REFERENCES tour_spots (tour_spot_id),
    CONSTRAINT uk_festival_tour_spots_festival_tour_spot UNIQUE (festival_id, tour_spot_id)
);

INSERT INTO festival_tour_spots (festival_id, tour_spot_id)
SELECT festival_id, tour_spot_id
FROM tour_spots;

DROP INDEX IF EXISTS idx_tour_spots_festival_id;

ALTER TABLE tour_spots
    DROP CONSTRAINT fk_tour_spots_festival,
    DROP COLUMN festival_id;

CREATE INDEX idx_festival_tour_spots_tour_spot_id ON festival_tour_spots (tour_spot_id);
