ALTER TABLE festivals
    ADD COLUMN l_dong_regn_cd VARCHAR(10),
    ADD COLUMN l_dong_signgu_cd VARCHAR(10),
    ADD COLUMN content_id BIGINT,
    ADD COLUMN operation_hours VARCHAR(50),
    ADD COLUMN program TEXT;

ALTER TABLE festivals
    ALTER COLUMN phone TYPE VARCHAR(100);

ALTER TABLE tour_spots
    ADD COLUMN content_id BIGINT,
    ADD COLUMN image_url TEXT,
    ADD COLUMN address VARCHAR(255),
    ADD COLUMN l_dong_regn_cd VARCHAR(10),
    ADD COLUMN l_dong_signgu_cd VARCHAR(10),
    ADD COLUMN phone VARCHAR(100),
    ADD COLUMN api_modified_at VARCHAR(14);

CREATE UNIQUE INDEX uk_festivals_content_id ON festivals (content_id) WHERE content_id IS NOT NULL;
CREATE UNIQUE INDEX uk_tour_spots_content_id ON tour_spots (content_id) WHERE content_id IS NOT NULL;

CREATE TABLE festival_tour_spots (
    festival_tour_spot_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    festival_id BIGINT NOT NULL,
    tour_spot_id BIGINT NOT NULL,
    CONSTRAINT pk_festival_tour_spots PRIMARY KEY (festival_tour_spot_id),
    CONSTRAINT fk_festival_tour_spots_festival FOREIGN KEY (festival_id) REFERENCES festivals (festival_id),
    CONSTRAINT fk_festival_tour_spots_tour_spot FOREIGN KEY (tour_spot_id) REFERENCES tour_spots (tour_spot_id),
    CONSTRAINT uk_festival_tour_spots_festival_tour_spot UNIQUE (festival_id, tour_spot_id)
);

INSERT INTO festival_tour_spots (festival_id, tour_spot_id)
SELECT festival_id, tour_spot_id
FROM tour_spots;

DROP INDEX IF EXISTS idx_tour_spots_festival_id;

ALTER TABLE tour_spots
    DROP CONSTRAINT fk_tour_spots_festival,
    DROP COLUMN festival_id;

CREATE INDEX idx_festival_tour_spots_tour_spot_id ON festival_tour_spots (tour_spot_id);

CREATE TABLE tour_spot_visits (
    tour_spot_visit_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    tour_spot_id BIGINT NOT NULL,
    status VARCHAR(10) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    ended_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_tour_spot_visits PRIMARY KEY (tour_spot_visit_id),
    CONSTRAINT fk_tour_spot_visits_member FOREIGN KEY (member_id) REFERENCES members (member_id),
    CONSTRAINT fk_tour_spot_visits_tour_spot FOREIGN KEY (tour_spot_id) REFERENCES tour_spots (tour_spot_id)
);

CREATE INDEX idx_tour_spot_visits_member_id ON tour_spot_visits (member_id);
CREATE INDEX idx_tour_spot_visits_expires_at ON tour_spot_visits (expires_at);
CREATE UNIQUE INDEX uk_tour_spot_visits_member_visiting
    ON tour_spot_visits (member_id)
    WHERE status = 'VISITING';
